### ISSUE TITLE
Replace binding with command

### ISSUE THREAD

**Issue by DigitalZilla** [Team3309/FRC2021-Offseason#12]
https://github.com/Team3309/FRC2021-Offseason/blob/894248e37c6267369d2eabc82c6ecf11a0ed7a7b/src/main/java/frc/robot/RobotContainer.java#L57

All bindings should use commands. Nothing should grab a system and manipulate it directly.

**Comment by MarkGhebrial** [comment]
I believe that passing a method into a binding creates an instant command. See https://docs.wpilib.org/en/stable/docs/software/commandbased/convenience-features.html#inlined-command-example

**Comment by MarkGhebrial** [comment]
I have confirmed the above:

From [edu.wpi.first.wpilibj2.command.button.Trigger.java](https://github.com/wpilibsuite/allwpilib/blob/main/wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Trigger.java), line 98
```
  /**
   * Runs the given runnable whenever the trigger just becomes active.
   *
   * @param toRun the runnable to run
   * @param requirements the required subsystems
   * @return this trigger, so calls can be chained
   */
  public Trigger whenActive(final Runnable toRun, Subsystem... requirements) {
    return whenActive(new InstantCommand(toRun, requirements));
  }
```

**Comment by DigitalZilla** [comment]
Yup, you are correct. Though, you will have to pass in the subsystem requirements or the command won't be able to use it.
`.whenPressed(() -> climber.deploy(), climber);`

**Comment by MarkGhebrial** [comment]
Good catch
